POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog 5",
    "author": "Dan Simmons",
    "url": "http://carrioncomfort.com",
    "likes": 115,
    "userId": "6338f188bbae13f2bdb986c6"
}