DELETE http://localhost:3003/api/blogs/63392d851690b196bc68d2b3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uIiwiaWQiOiI2MzM4ZjE4OGJiYWUxM2YyYmRiOTg2YzYiLCJpYXQiOjE2NjQ2OTE5NzcsImV4cCI6MTY2NDY5NTU3N30.SMscZ-cXcNeLIvTBtg8hbTyGzv-KF1-S5dwwZ4-xDfQ